### ISSUE TITLE
federated learning

### ISSUE THREAD

**Issue by baobaochai** [ianzhang221/FedproxGNN-TFP#1]
Hi, I am a current PhD student and I am recently doing research on combining federal learning with graph neural networks. I saw your code on githu and feel that your research work is done very excellent, I came to inquire if you have published any article about this research, I want to study and learn it?If you are available, you can also contact me via email at bbchai_915@sdust.edu.cn.

**Comment by ianzhang221** [comment]
Hi, thank you very much for your appreciation, I am a graduate student, I am currently researching the field of combining federal learning with deep learning, this code work I did last year, the related paper I wrote has been submitted and is currently under review, probably will be published in September this year, if you want to study maybe you can leave a more&nbsp; convenient contact, we can communicate more.





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ianzhang221/FedproxGNN-TFP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月13日(星期天) 下午4:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ianzhang221/FedproxGNN-TFP] federated learning (Issue #1)





 
Hi, I am a current PhD student and I am recently doing research on combining federal learning with graph neural networks. I saw your code on githu and feel that your research work is done very excellent, I came to inquire if you have published any article about this research, I want to study and learn it?If you are available, you can also contact me via email at ***@***.***

**Comment by baobaochai** [comment]
> 



> Hi, thank you very much for your appreciation, I am a graduate student, I am currently researching the field of combining federal learning with deep learning, this code work I did last year, the related paper I wrote has been submitted and is currently under review, probably will be published in September this year, if you want to study maybe you can leave a more&nbsp; convenient contact, we can communicate more.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "ianzhang221/FedproxGNN-TFP" ***@***.***&gt;; 发送时间:&nbsp;2022年3月13日(星期天) 下午4:47 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[ianzhang221/FedproxGNN-TFP] federated learning (Issue #1) Hi, I am a current PhD student and I am recently doing research on combining federal learning with graph neural networks. I saw your code on githu and feel that your research work is done very excellent, I came to inquire if you have published any article about this research, I want to study and learn it?If you are available, you can also contact me via email at ***@***.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by baobaochai** [comment]
> > 
> 
> > Hi, thank you very much for your appreciation, I am a graduate student, I am currently researching the field of combining federal learning with deep learning, this code work I did last year, the related paper I wrote has been submitted and is currently under review, probably will be published in September this year, if you want to study maybe you can leave a more  convenient contact, we can communicate more.
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "ianzhang221/FedproxGNN-TFP" _**@**_._**>; 发送时间: 2022年3月13日(星期天) 下午4:47 _**@**_.**_>; _**@**_._**>; 主题: [ianzhang221/FedproxGNN-TFP] federated learning (Issue #1) Hi, I am a current PhD student and I am recently doing research on combining federal learning with graph neural networks. I saw your code on githu and feel that your research work is done very excellent, I came to inquire if you have published any article about this research, I want to study and learn it?If you are available, you can also contact me via email at _**@**_.**_ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.***>

Hello, I am sorry to see your reply only today, for the previous we talked about your research I still have some questions to communicate with you again, if you do not mind please add my WeChat ch1802183044, looking forward to further communication with you.
